### ISSUE TITLE
fix truncated osd2014_18s---ssu---otu_mapping.stats and osd2014_16s---ssu---otu_mapping.stats

### ISSUE THREAD

**Issue by renzok** [MicroB3-IS/osd-analysis#16]
This was reported in [issue 14](https://github.com/MicroB3-IS/osd-analysis/issues/14)

I got some strange stuff on "osd2014_18s---ssu---otu_mapping.stats" where some rows (567)
seems truncated and so is not possible to read the complete list of names of clustered sequences.

**Comment by ikostadi** [comment]
I tracked the error down and fixed it (petty MySQL details during export). Both files are now fixed and replaced. Here are direct links 
[osd2014_18s---ssu---otu_mapping.stats](https://zarafa.mpi-bremen.de/owncloud/public.php?service=files&t=26a3006e7eb05bb566064e21244ef116&path=/stats/data/osd2014_18s---ssu---otu_mapping.stats)
[osd2014_16s---ssu---otu_mapping.stats](https://zarafa.mpi-bremen.de/owncloud/public.php?service=files&t=2d36d9a0e44ca6860a580f9c99572c4d&path=/stats/data/osd2014_16s---ssu---otu_mapping.stats)
