### ISSUE TITLE
Biological File Identifiers in Environmental Metadata

### ISSUE THREAD

**Issue by yavorska** [MicroB3-IS/osd-analysis#26]
Hi All, 

I've been going through the updated environmental metadata files and have come across a problem regarding the biological data identifiers.

Previously the biological files were referenced by names such as ERR---, however the current files have ERS--- and SAMEA32--- columns without the ERR--- identifier (which is needed for sample identification). I can match them all one by one through the EBI site, http://www.ebi.ac.uk/ena/data/view/ERS667665, however this will take a long time and I'm sure there should be a faster way to get the mappings. 

Has anyone gone through these mappings themselves already or can anyone point me in the direction of a file where I could find them?

Cheers!
Olena

**Comment by genomewalker** [comment]
Hi Olena,
you can find the mapping file between the runs (ERR*) and the OSD labels in this [**file**](https://owncloud.mpi-bremen.de/index.php/s/eaB3ChiDG6i9C6M/download?path=%2F2014%2Femg&files=OSDlabel-to-ENArun-2015-11-19.tsv) 

We will update the github wiki ASAP.

Cheers!
Antonio

**Comment by yavorska** [comment]
Fantastic, thank you!

**Comment by renzok** [comment]
and docuemnted here for all https://github.com/MicroB3-IS/osd-analysis/wiki/Guide-to-OSD-2014-data#mapping-between-osd-metadata-and-ena-runs
