### ISSUE TITLE
Make silva-ngs analysis results for LGC data available

### ISSUE THREAD

**Issue by renzok** [MicroB3-IS/osd-analysis#3]
issue well known @ikostadi is working on it.

This issue is for tracking status.

**Comment by pbuttigieg** [comment]
Just as a side note, FASTAs with MED-compliant headers will be part of this export.

**Comment by ikostadi** [comment]
Done. See [this section](/MicroB3-IS/osd-analysis/wiki/Guide-to-OSD-2014-data#analysis-of-16s18s-rdna-from-main-sequence-data-set-by-lgc) of the [OSD 2014 data guide](/MicroB3-IS/osd-analysis/wiki/Guide-to-OSD-2014-data).
