### ISSUE TITLE
Links on OSD wiki are dead....

### ISSUE THREAD

**Issue by vaulot** [MicroB3-IS/osd-analysis#33]
Hello

All the links to http://mb3is.megx.net/ seems to be dead... Is it temporary or are the files stored elsewhere.  Would it possible for you to store the OSD data on some kind of support that is permanent and public such as Figshare or something similar. This is very frustrating.

Thanks in advance.  Daniel

**Comment by genomewalker** [comment]
Hi Daniel,
can you try now? They should be working.

Cheers
Antonio

**Comment by vaulot** [comment]
Dear Antonio

Thanks a lot. It works fine now.  All the best.  Daniel
