### ISSUE TITLE
Where are the data now?

### ISSUE THREAD

**Issue by mkarlik93** [MicroB3-IS/osd-analysis#34]
Dear all,

I would like to use your generously shared workable data (16S, 18S and contigs) but, all links are corrupted. 

Could you send me to the right ones?

Best regards,

Michal

**Comment by ikostadi** [comment]
Dear Michal,

apologies for the inconvenience. We will solve the issue ASAP and let you know.

Best,
Ivo

**Comment by ikostadi** [comment]
Dear Michal,

we have fixed the problem, the data is accessible again.

Best,
Ivo
