### ISSUE TITLE
Raw fastq files for the Life Watch data set of 2014 (V4-V9) ?

### ISSUE THREAD

**Issue by vaulot** [MicroB3-IS/osd-analysis#38]
Is there a link somewhere to the raw fastq R1 and R2 files for the LifeWatch data ?  Thanks in advance.

**Comment by genomewalker** [comment]
Hi Daniel
they should be here https://mb3is.megx.net/osd-files?path=%2F2014%2Fdatasets%2Fraw%2Frdna

Look for the files with `_lw_` in the filename, i.e. [OSD2_R1_18S_V4_lw_raw.fastq.gz](https://mb3is.megx.net/index.php/s/XXqTven495RZmoA/download?path=%2F2014%2Fdatasets%2Fraw%2Frdna&files=OSD2_R1_18S_V4_lw_raw.fastq.gz)

Cheers
Antonio

**Comment by vaulot** [comment]
A big thanks Antonio, sometimes it is a bit challenging to find the files... Cheers.  Daniel
