### ISSUE TITLE
create  tables with otu taxa mapping for LGC 16S/18S datasets

### ISSUE THREAD

**Issue by renzok** [MicroB3-IS/osd-analysis#5]

**Comment by ikostadi** [comment]
Kudos to @genomewalker  for generating those. They can be found in the respective 'otu_table'
folders (direct links below). Be advised, the taxonomy is (quality) filtered. That means, if the quality score of the blast hit which was used to assign the taxonomy to the respective OUT reference is less than 93%, the taxonomy is set to 'No Relative'. The formula for the quality score is  (query_coverage+identity)/2 (see the respective analysis reports).
 
[osd2014_16S_lgc_otu_taxonomy.tsv.gz](https://zarafa.mpi-bremen.de/owncloud/public.php?service=files&t=2d36d9a0e44ca6860a580f9c99572c4d&path=/otu_table/osd2014_16S_lgc_otu_taxonomy.tsv.gz)
[osd2014_16S_lgc_otu_taxonomy.tsv.gz](https://zarafa.mpi-bremen.de/owncloud/public.php?service=files&t=26a3006e7eb05bb566064e21244ef116&path=//otu_table/osd2014_16S_lgc_otu_taxonomy.tsv.gz)
