### ISSUE TITLE
make SILVAngs analysis results for Australian samples available

### ISSUE THREAD

**Issue by renzok** [MicroB3-IS/osd-analysis#9]

**Comment by ikostadi** [comment]
This is now work in progress. ETA is June 3rd.

**Comment by ikostadi** [comment]
Sorry to report another delay - analysis is finally finished but exporting takes a while. New ETA is June 18th.

**Comment by ikostadi** [comment]
All major parts are now available (e.g. OTU tables, MED FASTA). For technical reasons, the following exports are still missing, but the SILVA Team is working on a solution:
- ".arb", ".fasta", ".ARF" files in the topmost directory
- sequence cluster exports (stats/sequence_cluster_map/data)

See [2014 OSD Data Guide](https://github.com/MicroB3-IS/osd-analysis/wiki/Guide-to-OSD-2014-data#analysis-of-workable-16s-rdna-dataset-from-australia-sequenced-by-rgc) for details and links.
